import { Calculator } from "./calculators";

/**
 * Complete Calculator Database - 25+ Evidence-Based Clinical Calculators
 * Smart Multi-Category Classification - Each calculator appears under all relevant specialties
 */

export const completeCalculators: Calculator[] = [
  // ============================================================================
  // CRITICAL CARE & SEPSIS
  // ============================================================================
  {
    id: "qsofa",
    name: "qSOFA Score",
    category: "Critical Care",
    categories: ["Critical Care", "Infectious Disease", "Emergency Medicine"],
    description: "Identifies high-risk patients for sepsis-related mortality outside the ICU",
    clinicalUses: ["Sepsis identification", "Mortality prediction", "ICU admission criteria"],
    inputs: [
      {
        id: "altered_mentation",
        label: "Altered Mentation",
        description: "Disorientation, lethargy, or agitation",
        type: "boolean",
      },
      {
        id: "respiratory_rate",
        label: "Respiratory Rate",
        description: "Breaths per minute (normal: 12-20)",
        type: "number",
        min: 0,
        max: 60,
      },
      {
        id: "systolic_bp",
        label: "Systolic Blood Pressure",
        description: "mmHg (normal: ≥100)",
        type: "number",
        min: 0,
        max: 250,
      },
    ],
    references: [
      {
        authors: "Singer M, et al.",
        year: 2016,
        title: "The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)",
        journal: "JAMA",
        volume: "315",
        pages: "801-810",
        citations: 3200,
        impactFactor: 41.9,
      },
      {
        authors: "Seymour CW, et al.",
        year: 2016,
        title: "Assessment of Clinical Criteria for Sepsis",
        journal: "JAMA",
        volume: "315",
        pages: "775-787",
        citations: 2500,
        impactFactor: 41.9,
      },
    ],
  },

  {
    id: "sofa",
    name: "SOFA Score",
    category: "Critical Care",
    categories: ["Critical Care", "Intensive Care", "Emergency Medicine"],
    description: "Sequential Organ Failure Assessment - Predicts ICU mortality and organ dysfunction",
    clinicalUses: ["ICU mortality prediction", "Organ dysfunction assessment", "Treatment response"],
    inputs: [
      {
        id: "respiration",
        label: "Respiratory Component",
        description: "PaO2/FiO2 ratio or mechanical ventilation",
        type: "select",
        options: ["PaO2/FiO2 ≥400", "PaO2/FiO2 300-399", "PaO2/FiO2 200-299 (intubated)", "PaO2/FiO2 <100 (intubated)"],
      },
      {
        id: "coagulation",
        label: "Coagulation",
        description: "Platelet count (×10³/μL)",
        type: "number",
        min: 0,
        max: 500,
      },
      {
        id: "liver",
        label: "Liver Function",
        description: "Bilirubin (mg/dL)",
        type: "number",
        min: 0,
        max: 30,
      },
      {
        id: "cardiovascular",
        label: "Cardiovascular",
        description: "Hypotension requirement",
        type: "select",
        options: ["No hypotension", "MAP <70 mmHg", "Dopamine ≤5 or dobutamine", "Dopamine >5 or epinephrine/norepinephrine"],
      },
      {
        id: "cns",
        label: "CNS (Glasgow Coma Scale)",
        description: "GCS Score",
        type: "number",
        min: 3,
        max: 15,
      },
      {
        id: "renal",
        label: "Renal Function",
        description: "Creatinine (mg/dL) or urine output",
        type: "number",
        min: 0,
        max: 10,
      },
    ],
    references: [
      {
        authors: "Vincent JL, et al.",
        year: 1996,
        title: "The SOFA (Sepsis-related Organ Failure Assessment) score to describe organ dysfunction/failure",
        journal: "Intensive Care Medicine",
        volume: "22",
        pages: "707-710",
        citations: 1800,
        impactFactor: 15.2,
      },
    ],
  },

  {
    id: "apache2",
    name: "APACHE II Score",
    category: "Critical Care",
    categories: ["Critical Care", "Intensive Care"],
    description: "Acute Physiology and Chronic Health Evaluation - ICU mortality prediction",
    clinicalUses: ["ICU severity assessment", "Mortality prediction", "Treatment outcomes"],
    inputs: [
      {
        id: "temperature",
        label: "Temperature (°C)",
        type: "number",
        min: 25,
        max: 45,
      },
      {
        id: "map",
        label: "Mean Arterial Pressure (mmHg)",
        type: "number",
        min: 0,
        max: 200,
      },
      {
        id: "hr",
        label: "Heart Rate (bpm)",
        type: "number",
        min: 0,
        max: 300,
      },
      {
        id: "rr",
        label: "Respiratory Rate (breaths/min)",
        type: "number",
        min: 0,
        max: 60,
      },
      {
        id: "fio2",
        label: "FiO2 (%)",
        type: "number",
        min: 21,
        max: 100,
      },
      {
        id: "ph",
        label: "Arterial pH",
        type: "number",
        min: 6.8,
        max: 8.0,
      },
      {
        id: "sodium",
        label: "Sodium (mEq/L)",
        type: "number",
        min: 100,
        max: 180,
      },
      {
        id: "potassium",
        label: "Potassium (mEq/L)",
        type: "number",
        min: 1,
        max: 10,
      },
      {
        id: "creatinine",
        label: "Creatinine (mg/dL)",
        type: "number",
        min: 0,
        max: 10,
      },
      {
        id: "hematocrit",
        label: "Hematocrit (%)",
        type: "number",
        min: 10,
        max: 60,
      },
      {
        id: "wbc",
        label: "WBC (×10³/μL)",
        type: "number",
        min: 0,
        max: 100,
      },
      {
        id: "gcs",
        label: "Glasgow Coma Scale",
        type: "number",
        min: 3,
        max: 15,
      },
    ],
    references: [
      {
        authors: "Knaus WA, et al.",
        year: 1985,
        title: "APACHE II: A severity of disease classification system",
        journal: "Critical Care Medicine",
        volume: "13",
        pages: "818-829",
        citations: 2200,
        impactFactor: 8.5,
      },
    ],
  },

  // ============================================================================
  // CARDIOLOGY & VASCULAR
  // ============================================================================
  {
    id: "heart",
    name: "HEART Score",
    category: "Cardiology",
    categories: ["Cardiology", "Emergency Medicine", "Chest Pain"],
    description: "Chest pain risk assessment - Identifies low-risk patients safe for discharge",
    clinicalUses: ["ACS risk assessment", "Admission decisions", "Discharge safety"],
    inputs: [
      {
        id: "history",
        label: "History of Presenting Complaint",
        type: "select",
        options: ["Typical angina", "Atypical angina", "Non-anginal chest pain"],
      },
      {
        id: "ecg",
        label: "ECG Changes",
        type: "select",
        options: ["Normal", "Nonspecific changes", "Ischemic changes"],
      },
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 0,
        max: 120,
      },
      {
        id: "risk_factors",
        label: "Risk Factors for CAD",
        type: "select",
        options: ["No known risk factors", "1-2 risk factors", "3+ risk factors or history of CAD"],
      },
      {
        id: "troponin",
        label: "Initial Troponin",
        type: "select",
        options: ["≤0.01 ng/mL", "0.01-0.03 ng/mL", ">0.03 ng/mL"],
      },
    ],
    references: [
      {
        authors: "Six AJ, et al.",
        year: 2008,
        title: "Chest pain in the emergency room: value of the HEART score",
        journal: "Netherlands Heart Journal",
        volume: "16",
        pages: "191-196",
        citations: 1200,
        impactFactor: 2.1,
      },
    ],
  },

  {
    id: "cha2ds2vasc",
    name: "CHA₂DS₂-VASc Score",
    category: "Cardiology",
    categories: ["Cardiology", "Neurology", "Stroke Prevention"],
    description: "Stroke risk in atrial fibrillation - Guides anticoagulation decisions",
    clinicalUses: ["Stroke risk assessment", "Anticoagulation decisions", "AF management"],
    inputs: [
      {
        id: "chf",
        label: "Congestive Heart Failure",
        type: "boolean",
      },
      {
        id: "hypertension",
        label: "Hypertension",
        type: "boolean",
      },
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 0,
        max: 120,
      },
      {
        id: "diabetes",
        label: "Diabetes",
        type: "boolean",
      },
      {
        id: "stroke",
        label: "Stroke/TIA/Thromboembolism",
        type: "boolean",
      },
      {
        id: "vascular",
        label: "Vascular Disease",
        type: "boolean",
      },
      {
        id: "sex",
        label: "Female Sex",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Lip GY, et al.",
        year: 2010,
        title: "Refining clinical risk stratification for predicting stroke and thromboembolism in atrial fibrillation",
        journal: "European Heart Journal",
        volume: "31",
        pages: "2623-2632",
        citations: 2800,
        impactFactor: 29.4,
      },
    ],
  },

  {
    id: "hasbled",
    name: "HAS-BLED Score",
    category: "Cardiology",
    categories: ["Cardiology", "Neurology", "Gastroenterology"],
    description: "Bleeding risk in atrial fibrillation - Assesses anticoagulation safety",
    clinicalUses: ["Bleeding risk assessment", "Anticoagulation safety", "AF management"],
    inputs: [
      {
        id: "hypertension",
        label: "Hypertension (uncontrolled)",
        type: "boolean",
      },
      {
        id: "renal_liver",
        label: "Abnormal Renal/Liver Function",
        type: "boolean",
      },
      {
        id: "stroke",
        label: "Stroke History",
        type: "boolean",
      },
      {
        id: "bleeding",
        label: "Bleeding History",
        type: "boolean",
      },
      {
        id: "labile_inr",
        label: "Labile INR",
        type: "boolean",
      },
      {
        id: "elderly",
        label: "Age >65 years",
        type: "boolean",
      },
      {
        id: "drugs_alcohol",
        label: "Drugs or Alcohol Use",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Pisters R, et al.",
        year: 2010,
        title: "A novel user-friendly score to assess 1-year risk of major bleeding in patients on oral anticoagulants",
        journal: "Chest",
        volume: "135",
        pages: "369-376",
        citations: 1500,
        impactFactor: 9.2,
      },
    ],
  },

  {
    id: "timi",
    name: "TIMI Risk Score",
    category: "Cardiology",
    categories: ["Cardiology", "Emergency Medicine"],
    description: "Acute Coronary Syndrome risk - Predicts 14-day mortality and complications",
    clinicalUses: ["ACS risk stratification", "Mortality prediction", "Treatment decisions"],
    inputs: [
      {
        id: "age",
        label: "Age ≥65 years",
        type: "boolean",
      },
      {
        id: "risk_factors",
        label: "≥3 CAD Risk Factors",
        type: "boolean",
      },
      {
        id: "stenosis",
        label: "Prior Coronary Stenosis",
        type: "boolean",
      },
      {
        id: "aspirin",
        label: "Aspirin Use in Last 7 Days",
        type: "boolean",
      },
      {
        id: "angina",
        label: "Severe Angina (≥2 episodes in 24h)",
        type: "boolean",
      },
      {
        id: "st_changes",
        label: "ST Segment Changes",
        type: "boolean",
      },
      {
        id: "troponin",
        label: "Elevated Troponin",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Antman EM, et al.",
        year: 2000,
        title: "The TIMI risk score for unstable angina/non-ST elevation MI",
        journal: "JAMA",
        volume: "284",
        pages: "835-842",
        citations: 2100,
        impactFactor: 41.9,
      },
    ],
  },

  {
    id: "framingham",
    name: "Framingham Risk Score",
    category: "Cardiology",
    categories: ["Cardiology", "Prevention", "Primary Care"],
    description: "10-year cardiovascular disease risk - Guides preventive therapy",
    clinicalUses: ["CVD risk assessment", "Prevention decisions", "Statin therapy"],
    inputs: [
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 30,
        max: 90,
      },
      {
        id: "sex",
        label: "Sex",
        type: "select",
        options: ["Male", "Female"],
      },
      {
        id: "total_cholesterol",
        label: "Total Cholesterol (mg/dL)",
        type: "number",
        min: 100,
        max: 400,
      },
      {
        id: "hdl",
        label: "HDL Cholesterol (mg/dL)",
        type: "number",
        min: 20,
        max: 100,
      },
      {
        id: "sbp",
        label: "Systolic BP (mmHg)",
        type: "number",
        min: 80,
        max: 200,
      },
      {
        id: "diabetes",
        label: "Diabetes",
        type: "boolean",
      },
      {
        id: "smoking",
        label: "Current Smoker",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Wilson PW, et al.",
        year: 1998,
        title: "Prediction of coronary heart disease using risk factor categories",
        journal: "Circulation",
        volume: "97",
        pages: "1837-1847",
        citations: 3500,
        impactFactor: 24.3,
      },
    ],
  },

  {
    id: "ascvd",
    name: "ASCVD Risk Calculator",
    category: "Cardiology",
    categories: ["Cardiology", "Prevention", "Primary Care"],
    description: "Atherosclerotic cardiovascular disease risk - Updated Framingham model",
    clinicalUses: ["ASCVD risk assessment", "Statin therapy decisions", "Prevention"],
    inputs: [
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 40,
        max: 90,
      },
      {
        id: "sex",
        label: "Sex",
        type: "select",
        options: ["Male", "Female"],
      },
      {
        id: "race",
        label: "Race/Ethnicity",
        type: "select",
        options: ["White", "African American", "Hispanic", "Asian"],
      },
      {
        id: "total_cholesterol",
        label: "Total Cholesterol (mg/dL)",
        type: "number",
        min: 100,
        max: 400,
      },
      {
        id: "hdl",
        label: "HDL Cholesterol (mg/dL)",
        type: "number",
        min: 20,
        max: 100,
      },
      {
        id: "sbp",
        label: "Systolic BP (mmHg)",
        type: "number",
        min: 80,
        max: 200,
      },
      {
        id: "diabetes",
        label: "Diabetes",
        type: "boolean",
      },
      {
        id: "smoking",
        label: "Current Smoker",
        type: "boolean",
      },
      {
        id: "hypertension_treatment",
        label: "On Hypertension Treatment",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Goff DC, et al.",
        year: 2013,
        title: "2013 ACC/AHA Guideline on the Assessment of Cardiovascular Risk",
        journal: "Circulation",
        volume: "129",
        pages: "S49-S73",
        citations: 2600,
        impactFactor: 24.3,
      },
    ],
  },

  // ============================================================================
  // NEUROLOGY & STROKE
  // ============================================================================
  {
    id: "nihss",
    name: "NIHSS (NIH Stroke Scale)",
    category: "Neurology",
    categories: ["Neurology", "Stroke", "Emergency Medicine"],
    description: "Acute stroke severity assessment - Determines thrombolytic eligibility",
    clinicalUses: ["Stroke severity", "Thrombolytic decisions", "Outcome prediction"],
    inputs: [
      {
        id: "loc",
        label: "Level of Consciousness",
        type: "select",
        options: ["Alert", "Drowsy", "Obtunded", "Coma"],
      },
      {
        id: "loc_questions",
        label: "LOC - Questions (Month, Age)",
        type: "select",
        options: ["Both correct", "One correct", "Both incorrect"],
      },
      {
        id: "loc_commands",
        label: "LOC - Commands (Open/Close eyes, Fist)",
        type: "select",
        options: ["Both correct", "One correct", "Both incorrect"],
      },
      {
        id: "gaze",
        label: "Gaze",
        type: "select",
        options: ["Normal", "Partial gaze palsy", "Forced deviation"],
      },
      {
        id: "vision",
        label: "Visual Fields",
        type: "select",
        options: ["No loss", "Partial hemianopia", "Complete hemianopia", "Bilateral hemianopia"],
      },
      {
        id: "facial_palsy",
        label: "Facial Palsy",
        type: "select",
        options: ["Normal", "Minor", "Partial", "Complete"],
      },
      {
        id: "motor_arm",
        label: "Motor Arm",
        type: "select",
        options: ["No drift", "Drift", "Can't resist gravity", "No effort"],
      },
      {
        id: "motor_leg",
        label: "Motor Leg",
        type: "select",
        options: ["No drift", "Drift", "Can't resist gravity", "No effort"],
      },
      {
        id: "limb_ataxia",
        label: "Limb Ataxia",
        type: "select",
        options: ["Absent", "Present in one limb", "Present in two limbs"],
      },
      {
        id: "sensory",
        label: "Sensory",
        type: "select",
        options: ["Normal", "Mild loss", "Severe loss"],
      },
      {
        id: "language",
        label: "Language",
        type: "select",
        options: ["Normal", "Mild aphasia", "Severe aphasia", "Mute/global aphasia"],
      },
      {
        id: "dysarthria",
        label: "Dysarthria",
        type: "select",
        options: ["Normal", "Mild", "Severe"],
      },
      {
        id: "extinction",
        label: "Extinction/Inattention",
        type: "select",
        options: ["Normal", "Mild", "Severe"],
      },
    ],
    references: [
      {
        authors: "Brott T, et al.",
        year: 1989,
        title: "Measurements of acute cerebral infarction: a clinical examination scale",
        journal: "Stroke",
        volume: "20",
        pages: "864-870",
        citations: 2400,
        impactFactor: 6.2,
      },
    ],
  },

  {
    id: "abcd2",
    name: "ABCD2 Score",
    category: "Neurology",
    categories: ["Neurology", "Stroke Prevention"],
    description: "TIA/Stroke risk after TIA - Guides urgent imaging and treatment",
    clinicalUses: ["TIA risk assessment", "Imaging urgency", "Treatment decisions"],
    inputs: [
      {
        id: "age",
        label: "Age ≥60 years",
        type: "boolean",
      },
      {
        id: "bp",
        label: "Blood Pressure ≥140/90 mmHg",
        type: "boolean",
      },
      {
        id: "clinical",
        label: "Clinical Features",
        type: "select",
        options: ["Speech disturbance only", "Unilateral weakness"],
      },
      {
        id: "duration",
        label: "Duration of Symptoms",
        type: "select",
        options: ["<10 minutes", "10-59 minutes", "≥60 minutes"],
      },
      {
        id: "diabetes",
        label: "Diabetes",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Johnston SC, et al.",
        year: 2007,
        title: "Validation and refinement of scores to predict very early stroke risk after transient ischemic attack",
        journal: "Lancet",
        volume: "369",
        pages: "283-292",
        citations: 1400,
        impactFactor: 60.0,
      },
    ],
  },

  // ============================================================================
  // RESPIRATORY
  // ============================================================================
  {
    id: "curb65",
    name: "CURB-65 Score",
    category: "Respiratory",
    categories: ["Respiratory", "Infectious Disease", "Emergency Medicine"],
    description: "Pneumonia severity - Determines admission vs outpatient management",
    clinicalUses: ["Pneumonia severity", "Admission decisions", "Mortality prediction"],
    inputs: [
      {
        id: "confusion",
        label: "Confusion",
        type: "boolean",
      },
      {
        id: "urea",
        label: "Urea >7 mmol/L",
        type: "boolean",
      },
      {
        id: "rr",
        label: "Respiratory Rate ≥30",
        type: "boolean",
      },
      {
        id: "bp",
        label: "Systolic BP <90 or Diastolic <60",
        type: "boolean",
      },
      {
        id: "age",
        label: "Age ≥65 years",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Lim WS, et al.",
        year: 2003,
        title: "Defining community acquired pneumonia severity on presentation to hospital",
        journal: "Respiratory Medicine",
        volume: "97",
        pages: "1175-1185",
        citations: 1600,
        impactFactor: 3.8,
      },
    ],
  },

  {
    id: "psi_port",
    name: "PSI/PORT Score",
    category: "Respiratory",
    categories: ["Respiratory", "Infectious Disease"],
    description: "Pneumonia Severity Index - Comprehensive mortality prediction",
    clinicalUses: ["Pneumonia risk stratification", "Admission decisions", "Mortality"],
    inputs: [
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 0,
        max: 120,
      },
      {
        id: "sex",
        label: "Male Sex",
        type: "boolean",
      },
      {
        id: "nursing_home",
        label: "Nursing Home Resident",
        type: "boolean",
      },
      {
        id: "comorbidity",
        label: "Comorbidity",
        type: "select",
        options: ["None", "Malignancy", "Liver disease", "CHF", "Cerebrovascular disease", "Renal disease", "Diabetes"],
      },
      {
        id: "altered_mental",
        label: "Altered Mental Status",
        type: "boolean",
      },
      {
        id: "rr",
        label: "Respiratory Rate (breaths/min)",
        type: "number",
        min: 0,
        max: 60,
      },
      {
        id: "sbp",
        label: "Systolic BP (mmHg)",
        type: "number",
        min: 0,
        max: 250,
      },
      {
        id: "temp",
        label: "Temperature (°C)",
        type: "number",
        min: 25,
        max: 45,
      },
      {
        id: "pulse",
        label: "Heart Rate (bpm)",
        type: "number",
        min: 0,
        max: 300,
      },
      {
        id: "ph",
        label: "Arterial pH",
        type: "number",
        min: 6.8,
        max: 8.0,
      },
      {
        id: "bun",
        label: "BUN (mg/dL)",
        type: "number",
        min: 0,
        max: 100,
      },
      {
        id: "sodium",
        label: "Sodium (mEq/L)",
        type: "number",
        min: 100,
        max: 180,
      },
      {
        id: "glucose",
        label: "Glucose (mg/dL)",
        type: "number",
        min: 0,
        max: 500,
      },
      {
        id: "hematocrit",
        label: "Hematocrit (%)",
        type: "number",
        min: 10,
        max: 60,
      },
      {
        id: "pao2",
        label: "PaO2 (mmHg)",
        type: "number",
        min: 20,
        max: 150,
      },
      {
        id: "pleural_effusion",
        label: "Pleural Effusion on CXR",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Fine MJ, et al.",
        year: 1997,
        title: "A prediction rule to identify low-risk patients with community-acquired pneumonia",
        journal: "New England Journal of Medicine",
        volume: "336",
        pages: "243-250",
        citations: 2800,
        impactFactor: 88.7,
      },
    ],
  },

  // ============================================================================
  // RENAL & HEPATIC
  // ============================================================================
  {
    id: "ckd_epi",
    name: "CKD-EPI GFR",
    category: "Renal",
    categories: ["Renal", "Nephrology", "Drug Dosing"],
    description: "Estimated Glomerular Filtration Rate - Kidney function assessment",
    clinicalUses: ["Renal function assessment", "Drug dosing", "CKD staging"],
    inputs: [
      {
        id: "creatinine",
        label: "Serum Creatinine (mg/dL)",
        type: "number",
        min: 0.1,
        max: 10,
      },
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 0,
        max: 120,
      },
      {
        id: "sex",
        label: "Sex",
        type: "select",
        options: ["Male", "Female"],
      },
      {
        id: "race",
        label: "Race",
        type: "select",
        options: ["Non-Black", "Black"],
      },
    ],
    references: [
      {
        authors: "Levey AS, et al.",
        year: 2009,
        title: "A new equation to estimate glomerular filtration rate",
        journal: "Annals of Internal Medicine",
        volume: "150",
        pages: "604-612",
        citations: 3200,
        impactFactor: 26.0,
      },
    ],
  },

  {
    id: "creatinine_clearance",
    name: "Creatinine Clearance",
    category: "Renal",
    categories: ["Renal", "Nephrology", "Drug Dosing"],
    description: "Cockcroft-Gault equation - Renal function for drug dosing",
    clinicalUses: ["Drug dosing adjustments", "Renal function", "Medication safety"],
    inputs: [
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 0,
        max: 120,
      },
      {
        id: "weight",
        label: "Weight (kg)",
        type: "number",
        min: 20,
        max: 200,
      },
      {
        id: "sex",
        label: "Sex",
        type: "select",
        options: ["Male", "Female"],
      },
      {
        id: "creatinine",
        label: "Serum Creatinine (mg/dL)",
        type: "number",
        min: 0.1,
        max: 10,
      },
    ],
    references: [
      {
        authors: "Cockcroft DW, Gault MH",
        year: 1976,
        title: "Prediction of creatinine clearance from serum creatinine",
        journal: "Nephron",
        volume: "16",
        pages: "31-41",
        citations: 4500,
        impactFactor: 2.8,
      },
    ],
  },

  {
    id: "meld",
    name: "MELD Score",
    category: "Hepatology",
    categories: ["Hepatology", "Gastroenterology", "Liver Disease"],
    description: "Model for End-Stage Liver Disease - Liver transplant priority",
    clinicalUses: ["Liver disease severity", "Transplant priority", "Mortality prediction"],
    inputs: [
      {
        id: "inr",
        label: "INR",
        type: "number",
        min: 0.8,
        max: 10,
      },
      {
        id: "creatinine",
        label: "Creatinine (mg/dL)",
        type: "number",
        min: 0.1,
        max: 10,
      },
      {
        id: "bilirubin",
        label: "Total Bilirubin (mg/dL)",
        type: "number",
        min: 0.1,
        max: 30,
      },
    ],
    references: [
      {
        authors: "Kamath PS, et al.",
        year: 2001,
        title: "A model to predict survival in patients with end-stage liver disease",
        journal: "Hepatology",
        volume: "33",
        pages: "464-470",
        citations: 2100,
        impactFactor: 14.8,
      },
    ],
  },

  // ============================================================================
  // GASTROENTEROLOGY
  // ============================================================================
  {
    id: "glasgow_blatchford",
    name: "Glasgow-Blatchford Score",
    category: "Gastroenterology",
    categories: ["Gastroenterology", "Emergency Medicine", "GI Bleeding"],
    description: "Upper GI bleed risk - Predicts need for intervention",
    clinicalUses: ["GI bleed severity", "Intervention prediction", "Admission decisions"],
    inputs: [
      {
        id: "blood_urea",
        label: "Blood Urea (mmol/L)",
        type: "number",
        min: 0,
        max: 50,
      },
      {
        id: "hemoglobin",
        label: "Hemoglobin (g/dL)",
        type: "number",
        min: 5,
        max: 18,
      },
      {
        id: "systolic_bp",
        label: "Systolic BP (mmHg)",
        type: "number",
        min: 50,
        max: 250,
      },
      {
        id: "pulse",
        label: "Pulse (bpm)",
        type: "number",
        min: 30,
        max: 200,
      },
      {
        id: "melena",
        label: "Melena Present",
        type: "boolean",
      },
      {
        id: "syncope",
        label: "Syncope",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Blatchford O, et al.",
        year: 2000,
        title: "A risk score to predict need for treatment for upper-gastrointestinal haemorrhage",
        journal: "Lancet",
        volume: "356",
        pages: "1318-1321",
        citations: 1200,
        impactFactor: 60.0,
      },
    ],
  },

  {
    id: "bisap",
    name: "BISAP Score",
    category: "Gastroenterology",
    categories: ["Gastroenterology", "Emergency Medicine", "Pancreatitis"],
    description: "Acute pancreatitis severity - Predicts mortality",
    clinicalUses: ["Pancreatitis severity", "Mortality prediction", "ICU admission"],
    inputs: [
      {
        id: "bun",
        label: "BUN >25 mg/dL",
        type: "boolean",
      },
      {
        id: "impaired_mental",
        label: "Impaired Mental Status",
        type: "boolean",
      },
      {
        id: "sirs",
        label: "SIRS Criteria (≥2)",
        type: "boolean",
      },
      {
        id: "age",
        label: "Age >60 years",
        type: "boolean",
      },
      {
        id: "pleural_effusion",
        label: "Pleural Effusion",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Wu BU, et al.",
        year: 2008,
        title: "The early prediction of mortality in acute pancreatitis",
        journal: "Archives of Internal Medicine",
        volume: "168",
        pages: "1996-2002",
        citations: 800,
        impactFactor: 18.3,
      },
    ],
  },

  // ============================================================================
  // INFECTIOUS DISEASE
  // ============================================================================
  {
    id: "centor",
    name: "Centor Score",
    category: "Infectious Disease",
    categories: ["Infectious Disease", "Emergency Medicine"],
    description: "Strep throat risk - Guides antibiotic therapy",
    clinicalUses: ["Strep throat risk", "Antibiotic decisions", "Testing decisions"],
    inputs: [
      {
        id: "fever",
        label: "Fever >38.3°C (101°F)",
        type: "boolean",
      },
      {
        id: "cough",
        label: "Cough Absent",
        type: "boolean",
      },
      {
        id: "exudate",
        label: "Pharyngeal Exudate",
        type: "boolean",
      },
      {
        id: "nodes",
        label: "Tender Anterior Cervical Nodes",
        type: "boolean",
      },
      {
        id: "age",
        label: "Age 3-14 years",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Centor RM, et al.",
        year: 1981,
        title: "The diagnosis of strep throat in adults in the emergency room",
        journal: "Medical Decision Making",
        volume: "1",
        pages: "239-246",
        citations: 900,
        impactFactor: 2.5,
      },
    ],
  },

  // ============================================================================
  // GERIATRIC & OTHER
  // ============================================================================
  {
    id: "news2",
    name: "NEWS2 Score",
    category: "Critical Care",
    categories: ["Critical Care", "Emergency Medicine", "General Medicine"],
    description: "National Early Warning Score - Detects clinical deterioration",
    clinicalUses: ["Early deterioration detection", "Escalation decisions", "Monitoring"],
    inputs: [
      {
        id: "respiration",
        label: "Respiratory Rate (breaths/min)",
        type: "number",
        min: 0,
        max: 60,
      },
      {
        id: "oxygen",
        label: "Oxygen Saturation (%)",
        type: "number",
        min: 50,
        max: 100,
      },
      {
        id: "temp",
        label: "Temperature (°C)",
        type: "number",
        min: 25,
        max: 45,
      },
      {
        id: "sbp",
        label: "Systolic BP (mmHg)",
        type: "number",
        min: 50,
        max: 250,
      },
      {
        id: "hr",
        label: "Heart Rate (bpm)",
        type: "number",
        min: 0,
        max: 300,
      },
      {
        id: "consciousness",
        label: "Consciousness",
        type: "select",
        options: ["Alert", "Verbal", "Pain", "Unresponsive"],
      },
    ],
    references: [
      {
        authors: "Royal College of Physicians",
        year: 2017,
        title: "National Early Warning Score (NEWS) 2",
        journal: "Clinical Guide",
        volume: "",
        pages: "",
        citations: 600,
        impactFactor: 0,
      },
    ],
  },

  {
    id: "glasgow_coma",
    name: "Glasgow Coma Scale",
    category: "Neurology",
    categories: ["Neurology", "Critical Care", "Trauma"],
    description: "Consciousness assessment - Evaluates neurological status",
    clinicalUses: ["Consciousness assessment", "Prognosis prediction", "Monitoring"],
    inputs: [
      {
        id: "eye_opening",
        label: "Eye Opening",
        type: "select",
        options: ["Spontaneous", "To verbal command", "To pain", "No response"],
      },
      {
        id: "verbal_response",
        label: "Verbal Response",
        type: "select",
        options: ["Oriented", "Confused", "Inappropriate", "Incomprehensible", "No response"],
      },
      {
        id: "motor_response",
        label: "Motor Response",
        type: "select",
        options: ["Obeys commands", "Localizes pain", "Withdraws", "Abnormal flexion", "Abnormal extension", "No response"],
      },
    ],
    references: [
      {
        authors: "Teasdale G, Jennett B",
        year: 1974,
        title: "Assessment of coma and impaired consciousness",
        journal: "Lancet",
        volume: "2",
        pages: "81-84",
        citations: 5000,
        impactFactor: 60.0,
      },
    ],
  },

  {
    id: "wells_dvt",
    name: "Wells' DVT Score",
    category: "Vascular",
    categories: ["Vascular", "Emergency Medicine", "Thromboembolism"],
    description: "Deep vein thrombosis risk - Guides imaging decisions",
    clinicalUses: ["DVT risk assessment", "Imaging decisions", "Treatment decisions"],
    inputs: [
      {
        id: "clinical_signs",
        label: "Clinical Signs of DVT",
        type: "boolean",
      },
      {
        id: "alternative",
        label: "Alternative Diagnosis Less Likely",
        type: "boolean",
      },
      {
        id: "heart_rate",
        label: "Heart Rate >100",
        type: "boolean",
      },
      {
        id: "immobilization",
        label: "Immobilization >3 days or Surgery",
        type: "boolean",
      },
      {
        id: "localized_tenderness",
        label: "Localized Tenderness",
        type: "boolean",
      },
      {
        id: "swelling",
        label: "Entire Leg Swelling",
        type: "boolean",
      },
      {
        id: "asymmetry",
        label: "Calf Swelling Asymmetry >3cm",
        type: "boolean",
      },
      {
        id: "pitting_edema",
        label: "Pitting Edema",
        type: "boolean",
      },
      {
        id: "collateral_veins",
        label: "Collateral Superficial Veins",
        type: "boolean",
      },
      {
        id: "previous_dvt",
        label: "Previous DVT",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Wells PS, et al.",
        year: 1997,
        title: "Accuracy of clinical assessment of deep-vein thrombosis",
        journal: "Lancet",
        volume: "345",
        pages: "1326-1330",
        citations: 1800,
        impactFactor: 60.0,
      },
    ],
  },

  {
    id: "wells_pe",
    name: "Wells' PE Score",
    category: "Vascular",
    categories: ["Vascular", "Emergency Medicine", "Thromboembolism"],
    description: "Pulmonary embolism risk - Guides imaging decisions",
    clinicalUses: ["PE risk assessment", "Imaging decisions", "Treatment decisions"],
    inputs: [
      {
        id: "clinical_dvt",
        label: "Clinical Signs of DVT",
        type: "boolean",
      },
      {
        id: "pe_likely",
        label: "PE Most Likely Diagnosis",
        type: "boolean",
      },
      {
        id: "heart_rate",
        label: "Heart Rate >100",
        type: "boolean",
      },
      {
        id: "immobilization",
        label: "Immobilization >3 days or Surgery",
        type: "boolean",
      },
      {
        id: "previous_vte",
        label: "Previous VTE",
        type: "boolean",
      },
      {
        id: "hemoptysis",
        label: "Hemoptysis",
        type: "boolean",
      },
      {
        id: "malignancy",
        label: "Malignancy",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Wells PS, et al.",
        year: 2000,
        title: "Derivation of a simple clinical model to categorize patients probability of pulmonary embolism",
        journal: "Thrombosis and Haemostasis",
        volume: "83",
        pages: "416-420",
        citations: 1500,
        impactFactor: 4.2,
      },
    ],
  },

  // ============================================================================
  // PERIOPERATIVE MEDICINE & ANESTHESIOLOGY
  // ============================================================================
  {
    id: "asa_physical_status",
    name: "ASA Physical Status Classification",
    category: "Perioperative Medicine",
    categories: ["Perioperative Medicine", "Anesthesiology", "Surgery"],
    description: "American Society of Anesthesiologists classification for perioperative risk assessment",
    clinicalUses: ["Perioperative risk stratification", "Anesthesia planning", "Surgical risk communication"],
    inputs: [
      {
        id: "asa_class",
        label: "ASA Physical Status Class",
        type: "select",
        options: [
          "I - Healthy patient",
          "II - Mild systemic disease",
          "III - Severe systemic disease",
          "IV - Severe disease that is constant threat to life",
          "V - Moribund patient not expected to survive without surgery",
          "VI - Brain-dead patient for organ donation",
        ],
      },
      {
        id: "emergency",
        label: "Emergency Surgery",
        description: "Add 'E' modifier for emergency procedures",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Doyle DJ, et al.",
        year: 2021,
        title: "American Society of Anesthesiologists Classification",
        journal: "StatPearls",
        volume: "NBK441940",
        pages: "1-8",
        citations: 450,
        impactFactor: 0,
      },
      {
        authors: "Mayhew D, et al.",
        year: 2019,
        title: "A review of ASA physical status - historical perspectives and modern developments",
        journal: "Anaesthesia",
        volume: "74",
        pages: "373-379",
        citations: 380,
        impactFactor: 7.5,
      },
    ],
  },

  {
    id: "rcri",
    name: "RCRI (Revised Cardiac Risk Index)",
    category: "Perioperative Medicine",
    categories: ["Perioperative Medicine", "Cardiology", "Anesthesiology"],
    description: "Lee Index - Predicts major cardiac complications after non-cardiac surgery",
    clinicalUses: ["Cardiac risk assessment", "Perioperative planning", "Risk stratification"],
    inputs: [
      {
        id: "high_risk_surgery",
        label: "High-Risk Surgery",
        description: "Intraperitoneal, intrathoracic, or suprainguinal vascular",
        type: "boolean",
      },
      {
        id: "ischemic_heart_disease",
        label: "History of Ischemic Heart Disease",
        description: "MI, positive stress test, angina, or Q waves on ECG",
        type: "boolean",
      },
      {
        id: "heart_failure",
        label: "History of Congestive Heart Failure",
        description: "Clinical CHF, pulmonary edema, or S3 gallop",
        type: "boolean",
      },
      {
        id: "cerebrovascular_disease",
        label: "History of Cerebrovascular Disease",
        description: "TIA or stroke",
        type: "boolean",
      },
      {
        id: "diabetes_insulin",
        label: "Diabetes on Insulin",
        type: "boolean",
      },
      {
        id: "renal_insufficiency",
        label: "Preoperative Creatinine >2 mg/dL",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Lee TH, et al.",
        year: 1999,
        title: "Derivation and prospective validation of a simple index for prediction of cardiac risk of major noncardiac surgery",
        journal: "Circulation",
        volume: "100",
        pages: "1043-1049",
        citations: 3200,
        impactFactor: 23.0,
      },
      {
        authors: "Duceppe E, et al.",
        year: 2017,
        title: "Canadian Cardiovascular Society Guidelines on Perioperative Cardiac Risk Assessment",
        journal: "Canadian Journal of Cardiology",
        volume: "33",
        pages: "17-32",
        citations: 580,
        impactFactor: 5.0,
      },
    ],
  },

  {
    id: "caprini_vte",
    name: "Caprini Score for VTE Risk",
    category: "Perioperative Medicine",
    categories: ["Perioperative Medicine", "Hematology", "Surgery"],
    description: "Assesses venous thromboembolism risk in surgical patients",
    clinicalUses: ["VTE prophylaxis", "Risk stratification", "Thromboprophylaxis decisions"],
    inputs: [
      {
        id: "age",
        label: "Age",
        type: "select",
        options: ["<41 years", "41-60 years", "61-74 years", "≥75 years"],
      },
      {
        id: "minor_surgery",
        label: "Minor Surgery Planned",
        type: "boolean",
      },
      {
        id: "major_surgery",
        label: "Major Surgery >45 minutes",
        type: "boolean",
      },
      {
        id: "bmi",
        label: "BMI >25",
        type: "boolean",
      },
      {
        id: "varicose_veins",
        label: "Varicose Veins",
        type: "boolean",
      },
      {
        id: "current_cancer",
        label: "Current Cancer",
        type: "boolean",
      },
      {
        id: "previous_vte",
        label: "Previous VTE",
        type: "boolean",
      },
      {
        id: "thrombophilia",
        label: "Known Thrombophilia",
        type: "boolean",
      },
      {
        id: "immobility",
        label: "Immobility/Bed Rest",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Caprini JA",
        year: 2005,
        title: "Thrombosis risk assessment as a guide to quality patient care",
        journal: "Disease-a-Month",
        volume: "51",
        pages: "70-78",
        citations: 850,
        impactFactor: 2.5,
      },
      {
        authors: "Pannucci CJ, et al.",
        year: 2017,
        title: "Validation of the Caprini risk assessment model",
        journal: "Journal of the American College of Surgeons",
        volume: "224",
        pages: "449-458",
        citations: 420,
        impactFactor: 6.5,
      },
    ],
  },

  {
    id: "pesi",
    name: "PESI (Pulmonary Embolism Severity Index)",
    category: "Pulmonology",
    categories: ["Pulmonology", "Emergency Medicine", "Critical Care"],
    description: "Predicts 30-day mortality in pulmonary embolism - guides outpatient vs inpatient management",
    clinicalUses: ["PE severity assessment", "Disposition decisions", "Risk stratification"],
    inputs: [
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 0,
        max: 120,
      },
      {
        id: "male",
        label: "Male Sex",
        type: "boolean",
      },
      {
        id: "cancer",
        label: "History of Cancer",
        type: "boolean",
      },
      {
        id: "heart_failure",
        label: "History of Heart Failure",
        type: "boolean",
      },
      {
        id: "chronic_lung_disease",
        label: "Chronic Lung Disease",
        type: "boolean",
      },
      {
        id: "pulse",
        label: "Pulse ≥110 bpm",
        type: "boolean",
      },
      {
        id: "systolic_bp",
        label: "Systolic BP <100 mmHg",
        type: "boolean",
      },
      {
        id: "respiratory_rate",
        label: "Respiratory Rate ≥30/min",
        type: "boolean",
      },
      {
        id: "temperature",
        label: "Temperature <36°C",
        type: "boolean",
      },
      {
        id: "altered_mental",
        label: "Altered Mental Status",
        type: "boolean",
      },
      {
        id: "oxygen_sat",
        label: "Oxygen Saturation <90%",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Aujesky D, et al.",
        year: 2005,
        title: "Derivation and validation of a prognostic model for pulmonary embolism",
        journal: "American Journal of Respiratory and Critical Care Medicine",
        volume: "172",
        pages: "1041-1046",
        citations: 1850,
        impactFactor: 19.7,
      },
      {
        authors: "Jiménez D, et al.",
        year: 2007,
        title: "Simplification of the pulmonary embolism severity index for prognostication",
        journal: "Archives of Internal Medicine",
        volume: "167",
        pages: "470-475",
        citations: 920,
        impactFactor: 18.0,
      },
    ],
  },

  {
    id: "smart_cop",
    name: "SMART-COP Score",
    category: "Pulmonology",
    categories: ["Pulmonology", "Emergency Medicine", "Infectious Disease"],
    description: "Predicts need for intensive respiratory or vasopressor support in pneumonia",
    clinicalUses: ["ICU admission", "Severe pneumonia identification", "Risk stratification"],
    inputs: [
      {
        id: "systolic_bp",
        label: "Systolic BP <90 mmHg",
        type: "boolean",
      },
      {
        id: "multilobar",
        label: "Multilobar Chest X-ray Involvement",
        type: "boolean",
      },
      {
        id: "albumin",
        label: "Albumin <3.5 g/dL",
        type: "boolean",
      },
      {
        id: "respiratory_rate",
        label: "Respiratory Rate (age-adjusted)",
        description: "Age ≤50: RR ≥25 | Age >50: RR ≥30",
        type: "boolean",
      },
      {
        id: "tachycardia",
        label: "Tachycardia ≥125 bpm",
        type: "boolean",
      },
      {
        id: "confusion",
        label: "Confusion (new onset)",
        type: "boolean",
      },
      {
        id: "oxygen",
        label: "Low Oxygen",
        description: "Age ≤50: PaO2 <70 or SaO2 <93% | Age >50: PaO2 <60 or SaO2 <90%",
        type: "boolean",
      },
      {
        id: "ph",
        label: "Arterial pH <7.35",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Charles PG, et al.",
        year: 2008,
        title: "SMART-COP: a tool for predicting the need for intensive respiratory or vasopressor support",
        journal: "Clinical Infectious Diseases",
        volume: "47",
        pages: "375-384",
        citations: 680,
        impactFactor: 9.1,
      },
      {
        authors: "Chalmers JD, et al.",
        year: 2011,
        title: "Severity assessment tools for predicting mortality in hospitalised patients with pneumonia",
        journal: "Thorax",
        volume: "65",
        pages: "878-883",
        citations: 520,
        impactFactor: 11.0,
      },
    ],
  },

  // ============================================================================
  // HEPATOLOGY (EXPANDED)
  // ============================================================================
  {
    id: "child_pugh",
    name: "Child-Pugh Score",
    category: "Hepatology",
    categories: ["Hepatology", "Gastroenterology", "Critical Care"],
    description: "Classic liver disease severity classification - predicts mortality and surgical risk",
    clinicalUses: ["Cirrhosis severity", "Surgical risk", "Prognosis assessment"],
    inputs: [
      {
        id: "bilirubin",
        label: "Total Bilirubin (mg/dL)",
        type: "number",
        min: 0,
        max: 20,
      },
      {
        id: "albumin",
        label: "Serum Albumin (g/dL)",
        type: "number",
        min: 0,
        max: 6,
      },
      {
        id: "inr",
        label: "INR",
        type: "number",
        min: 0.8,
        max: 5,
      },
      {
        id: "ascites",
        label: "Ascites",
        type: "select",
        options: ["None", "Mild (controlled with diuretics)", "Moderate to severe (despite diuretics)"],
      },
      {
        id: "encephalopathy",
        label: "Hepatic Encephalopathy",
        type: "select",
        options: ["None", "Grade I-II (mild)", "Grade III-IV (severe)"],
      },
    ],
    references: [
      {
        authors: "Pugh RN, et al.",
        year: 1973,
        title: "Transection of the oesophagus for bleeding oesophageal varices",
        journal: "British Journal of Surgery",
        volume: "60",
        pages: "646-649",
        citations: 6800,
        impactFactor: 7.0,
      },
      {
        authors: "Cholongitas E, et al.",
        year: 2005,
        title: "A systematic review of the performance of the model for end-stage liver disease",
        journal: "Hepatology",
        volume: "44",
        pages: "1515-1527",
        citations: 1200,
        impactFactor: 17.4,
      },
    ],
  },

  {
    id: "fib4",
    name: "FIB-4 Index",
    category: "Hepatology",
    categories: ["Hepatology", "Gastroenterology", "Primary Care"],
    description: "Non-invasive liver fibrosis assessment - widely used for NAFLD and chronic hepatitis",
    clinicalUses: ["Fibrosis screening", "NAFLD assessment", "Cirrhosis risk"],
    inputs: [
      {
        id: "age",
        label: "Age (years)",
        type: "number",
        min: 18,
        max: 100,
      },
      {
        id: "ast",
        label: "AST (U/L)",
        type: "number",
        min: 0,
        max: 500,
      },
      {
        id: "alt",
        label: "ALT (U/L)",
        type: "number",
        min: 0,
        max: 500,
      },
      {
        id: "platelets",
        label: "Platelet Count (×10⁹/L)",
        type: "number",
        min: 0,
        max: 500,
      },
    ],
    references: [
      {
        authors: "Sterling RK, et al.",
        year: 2006,
        title: "Development of a simple noninvasive index to predict significant fibrosis",
        journal: "Hepatology",
        volume: "43",
        pages: "1317-1325",
        citations: 2400,
        impactFactor: 17.4,
      },
      {
        authors: "Shah AG, et al.",
        year: 2009,
        title: "Comparison of noninvasive markers of fibrosis in patients with nonalcoholic fatty liver disease",
        journal: "Clinical Gastroenterology and Hepatology",
        volume: "7",
        pages: "1104-1112",
        citations: 1650,
        impactFactor: 10.4,
      },
    ],
  },

  {
    id: "meld_na",
    name: "MELD-Na Score",
    category: "Hepatology",
    categories: ["Hepatology", "Gastroenterology", "Transplant Surgery"],
    description: "Enhanced MELD with serum sodium - improved mortality prediction for liver transplant allocation",
    clinicalUses: ["Transplant prioritization", "Mortality prediction", "Waitlist management"],
    inputs: [
      {
        id: "creatinine",
        label: "Creatinine (mg/dL)",
        type: "number",
        min: 0.5,
        max: 10,
      },
      {
        id: "bilirubin",
        label: "Total Bilirubin (mg/dL)",
        type: "number",
        min: 0.5,
        max: 30,
      },
      {
        id: "inr",
        label: "INR",
        type: "number",
        min: 0.8,
        max: 5,
      },
      {
        id: "sodium",
        label: "Serum Sodium (mEq/L)",
        type: "number",
        min: 120,
        max: 150,
      },
      {
        id: "dialysis",
        label: "Dialysis Twice in Past Week",
        type: "boolean",
      },
    ],
    references: [
      {
        authors: "Biggins SW, et al.",
        year: 2006,
        title: "Evidence-based incorporation of serum sodium concentration into MELD",
        journal: "Gastroenterology",
        volume: "130",
        pages: "1652-1660",
        citations: 850,
        impactFactor: 22.7,
      },
      {
        authors: "Kim WR, et al.",
        year: 2008,
        title: "Hyponatremia and mortality among patients on the liver-transplant waiting list",
        journal: "New England Journal of Medicine",
        volume: "359",
        pages: "1018-1026",
        citations: 1200,
        impactFactor: 74.7,
      },
    ],
  },

  {
    id: "apri",
    name: "APRI Score",
    category: "Hepatology",
    categories: ["Hepatology", "Gastroenterology", "Infectious Disease"],
    description: "AST to Platelet Ratio Index - simple fibrosis assessment for chronic liver disease",
    clinicalUses: ["Fibrosis screening", "Hepatitis C assessment", "Cirrhosis prediction"],
    inputs: [
      {
        id: "ast",
        label: "AST (U/L)",
        type: "number",
        min: 0,
        max: 500,
      },
      {
        id: "ast_upper_limit",
        label: "AST Upper Limit of Normal (U/L)",
        description: "Typically 40 U/L",
        type: "number",
        min: 20,
        max: 60,
      },
      {
        id: "platelets",
        label: "Platelet Count (×10⁹/L)",
        type: "number",
        min: 0,
        max: 500,
      },
    ],
    references: [
      {
        authors: "Wai CT, et al.",
        year: 2003,
        title: "A simple noninvasive index can predict both significant fibrosis and cirrhosis",
        journal: "Hepatology",
        volume: "38",
        pages: "518-526",
        citations: 1900,
        impactFactor: 17.4,
      },
      {
        authors: "Lin ZH, et al.",
        year: 2011,
        title: "Performance of the aspartate aminotransferase-to-platelet ratio index",
        journal: "World Journal of Gastroenterology",
        volume: "17",
        pages: "1779-1789",
        citations: 680,
        impactFactor: 5.0,
      },
    ],
  },
];

export default completeCalculators;
