import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, AlertCircle, CheckCircle, TrendingUp, Download, Copy, Check, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { jsPDF } from "jspdf";

interface CalculationResult {
  score: number;
  riskLevel: "low" | "moderate" | "high" | "critical";
  riskPercentage: number;
  recommendations: string[];
  managementPathway: any;
  interpretation: string;
}

interface ResultsDisplayEnhancedProps {
  result: CalculationResult;
  calculatorName: string;
}

export function ResultsDisplayEnhanced({
  result,
  calculatorName,
}: ResultsDisplayEnhancedProps) {
  const [copied, setCopied] = useState(false);

  // Trigger install prompt after results are displayed
  useEffect(() => {
    // Check if this is the first calculation
    const hasCalculated = localStorage.getItem('first-calculation-done');
    if (!hasCalculated) {
      localStorage.setItem('first-calculation-done', 'true');
      // Dispatch custom event to show result install prompt
      const event = new CustomEvent('show-result-install-prompt');
      window.dispatchEvent(event);
    }
  }, []);

  // Color scheme with patterns for color-blind accessibility
  const getRiskColor = (level: string) => {
    switch (level) {
      case "low":
        return {
          bg: "bg-green-50",
          border: "border-green-200",
          text: "text-green-900",
          badge: "bg-green-100 text-green-800",
          pattern: "●", // Solid circle for low
          ariaLabel: "Low risk - safe",
        };
      case "moderate":
        return {
          bg: "bg-yellow-50",
          border: "border-yellow-200",
          text: "text-yellow-900",
          badge: "bg-yellow-100 text-yellow-800",
          pattern: "◐", // Half circle for moderate
          ariaLabel: "Moderate risk - caution advised",
        };
      case "high":
        return {
          bg: "bg-orange-50",
          border: "border-orange-200",
          text: "text-orange-900",
          badge: "bg-orange-100 text-orange-800",
          pattern: "◑", // Three-quarter for high
          ariaLabel: "High risk - intervention recommended",
        };
      case "critical":
        return {
          bg: "bg-red-50",
          border: "border-red-200",
          text: "text-red-900",
          badge: "bg-red-100 text-red-800",
          pattern: "◉", // Target for critical
          ariaLabel: "Critical risk - immediate action required",
        };
      default:
        return {
          bg: "bg-slate-50",
          border: "border-slate-200",
          text: "text-slate-900",
          badge: "bg-slate-100 text-slate-800",
          pattern: "○",
          ariaLabel: "Risk level unknown",
        };
    }
  };

  const getRiskIcon = (level: string) => {
    const iconProps = {
      className: "w-8 h-8",
      "aria-hidden": "true" as const,
    };

    switch (level) {
      case "low":
        return <CheckCircle {...iconProps} className={`${iconProps.className} text-green-600`} />;
      case "moderate":
        return <AlertCircle {...iconProps} className={`${iconProps.className} text-yellow-600`} />;
      case "high":
        return <AlertTriangle {...iconProps} className={`${iconProps.className} text-orange-600`} />;
      case "critical":
        return <AlertTriangle {...iconProps} className={`${iconProps.className} text-red-600`} />;
      default:
        return <CheckCircle {...iconProps} className={`${iconProps.className} text-slate-600`} />;
    }
  };

  const colors = getRiskColor(result.riskLevel);

  // Listen for custom event to show result install prompt
  useEffect(() => {
    const handleShowPrompt = () => {
      // This will be handled by EnhancedInstallPrompt component
    };
    window.addEventListener('show-result-install-prompt', handleShowPrompt);
    return () => window.removeEventListener('show-result-install-prompt', handleShowPrompt);
  }, []);

  // Generate plain text for clipboard/EMR
  const generatePlainText = () => {
    const timestamp = new Date().toLocaleString();
    const managementSteps = Array.isArray(result.managementPathway)
      ? result.managementPathway.map((step: any, idx: number) => `  ${idx + 1}. ${step.action} - ${step.rationale}`).join("\n")
      : result.managementPathway;

    return `
=== CLINICAL CALCULATOR RESULT ===
Calculator: ${calculatorName}
Date/Time: ${timestamp}

SCORE: ${result.score}
RISK LEVEL: ${result.riskLevel.toUpperCase()} (${result.riskPercentage}%)

CLINICAL INTERPRETATION:
${result.interpretation}

MANAGEMENT PATHWAY:
${managementSteps}

RECOMMENDATIONS:
${result.recommendations.map((rec) => `  ${rec}`).join("\n")}

---
Generated by MedResearch Academy Clinical Decision Support
Disclaimer: This is for clinical decision support only. Always verify with current guidelines.
`.trim();
  };

  // Copy to clipboard for EMR integration
  const handleCopyToClipboard = async () => {
    const text = generatePlainText();
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success("Copied to clipboard", {
        description: "Result copied for EMR documentation",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error("Failed to copy", {
        description: "Please try again or use manual selection",
      });
    }
  };

  // Download PDF functionality
  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);
      let y = margin;

      // Header
      doc.setFontSize(18);
      doc.setTextColor(30, 64, 175); // Blue
      doc.text(calculatorName, margin, y);
      y += 10;

      doc.setFontSize(9);
      doc.setTextColor(107, 114, 128); // Gray
      doc.text(`Generated: ${new Date().toLocaleString()} | MedResearch Academy`, margin, y);
      y += 15;

      // Score Box
      const boxColor: [number, number, number] = result.riskLevel === "low" ? [220, 252, 231] :
                       result.riskLevel === "moderate" ? [254, 249, 195] :
                       result.riskLevel === "high" ? [254, 215, 170] : [254, 202, 202];
      doc.setFillColor(boxColor[0], boxColor[1], boxColor[2]);
      doc.rect(margin, y, contentWidth, 40, 'F');

      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.text(`Score: ${result.score}`, margin + 10, y + 15);
      doc.text(`Risk: ${result.riskPercentage}%`, margin + 70, y + 15);
      doc.text(`Level: ${result.riskLevel.toUpperCase()}`, margin + 130, y + 15);
      y += 50;

      // Clinical Interpretation
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      doc.text("CLINICAL INTERPRETATION", margin, y);
      y += 7;

      doc.setFontSize(9);
      doc.setTextColor(0, 0, 0);
      const interpretationLines = doc.splitTextToSize(result.interpretation, contentWidth);
      doc.text(interpretationLines, margin, y);
      y += (interpretationLines.length * 5) + 10;

      // Management Pathway
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      doc.text("MANAGEMENT PATHWAY", margin, y);
      y += 7;

      doc.setFontSize(9);
      doc.setTextColor(0, 0, 0);
      if (Array.isArray(result.managementPathway)) {
        result.managementPathway.forEach((step: any, idx: number) => {
          const stepText = `${idx + 1}. ${step.action} - ${step.rationale}`;
          const stepLines = doc.splitTextToSize(stepText, contentWidth - 10);
          doc.text(stepLines, margin + 5, y);
          y += (stepLines.length * 5) + 3;
        });
      }
      y += 5;

      // Recommendations
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      doc.text("CLINICAL RECOMMENDATIONS", margin, y);
      y += 7;

      doc.setFontSize(9);
      doc.setTextColor(0, 0, 0);
      result.recommendations.forEach((rec: string) => {
        const recLines = doc.splitTextToSize(`✓ ${rec}`, contentWidth - 10);
        doc.text(recLines, margin + 5, y);
        y += (recLines.length * 5) + 3;
      });

      // Disclaimer
      y += 10;
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      const disclaimerText = "Disclaimer: This calculator is for clinical decision support only. It should not replace clinical judgment or professional medical advice.";
      const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth);
      doc.text(disclaimerLines, margin, y);

      // Save PDF
      const filename = `${calculatorName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(filename);

      toast.success("PDF Downloaded", {
        description: "Result saved as PDF file",
      });
    } catch (err) {
      console.error("PDF generation error:", err);
      toast.error("PDF generation failed", {
        description: "Please try the Print/PDF button instead",
      });
    }
  };

  // Print functionality
  const handlePrint = () => {
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${calculatorName} - Clinical Calculator Result</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #1a1a1a;
          }
          .header {
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 15px;
            margin-bottom: 20px;
          }
          .header h1 {
            margin: 0;
            color: #1e40af;
            font-size: 24px;
          }
          .header p {
            margin: 5px 0 0;
            color: #6b7280;
            font-size: 12px;
          }
          .result-box {
            background: ${result.riskLevel === "low" ? "#f0fdf4" : result.riskLevel === "moderate" ? "#fefce8" : result.riskLevel === "high" ? "#fff7ed" : "#fef2f2"};
            border: 2px solid ${result.riskLevel === "low" ? "#86efac" : result.riskLevel === "moderate" ? "#fde047" : result.riskLevel === "high" ? "#fdba74" : "#fca5a5"};
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
          }
          .score-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin-bottom: 20px;
          }
          .score-item {
            background: white;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 12px;
          }
          .score-label {
            font-size: 11px;
            color: #6b7280;
            text-transform: uppercase;
            font-weight: 600;
            margin-bottom: 5px;
          }
          .score-value {
            font-size: 24px;
            font-weight: bold;
            color: #1a1a1a;
          }
          .risk-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 999px;
            font-weight: 600;
            font-size: 12px;
            text-transform: uppercase;
            background: ${result.riskLevel === "low" ? "#dcfce7" : result.riskLevel === "moderate" ? "#fef9c3" : result.riskLevel === "high" ? "#fed7aa" : "#fecaca"};
            color: ${result.riskLevel === "low" ? "#166534" : result.riskLevel === "moderate" ? "#854d0e" : result.riskLevel === "high" ? "#c2410c" : "#b91c1c"};
          }
          .section {
            margin-bottom: 20px;
          }
          .section-title {
            font-size: 11px;
            color: #6b7280;
            text-transform: uppercase;
            font-weight: 600;
            margin-bottom: 10px;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 5px;
          }
          .interpretation {
            background: white;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 12px;
            margin-bottom: 15px;
          }
          .recommendation {
            display: flex;
            align-items: flex-start;
            gap: 10px;
            padding: 10px;
            background: white;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            margin-bottom: 8px;
          }
          .recommendation-check {
            width: 20px;
            height: 20px;
            border-radius: 50%;
            background: #3b82f6;
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            flex-shrink: 0;
          }
          .management-step {
            display: flex;
            align-items: flex-start;
            gap: 10px;
            margin-bottom: 10px;
          }
          .step-number {
            width: 24px;
            height: 24px;
            border-radius: 50%;
            background: #dbeafe;
            color: #2563eb;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            font-weight: bold;
            flex-shrink: 0;
          }
          .disclaimer {
            margin-top: 30px;
            padding: 15px;
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            font-size: 11px;
            color: #64748b;
          }
          .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 11px;
            color: #9ca3af;
          }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${calculatorName}</h1>
          <p>Generated: ${new Date().toLocaleString()} | MedResearch Academy Clinical Decision Support</p>
        </div>

        <div class="result-box">
          <div class="score-grid">
            <div class="score-item">
              <div class="score-label">Score</div>
              <div class="score-value">${result.score}</div>
            </div>
            <div class="score-item">
              <div class="score-label">Risk Percentage</div>
              <div class="score-value">${result.riskPercentage}%</div>
            </div>
            <div class="score-item">
              <div class="score-label">Risk Level</div>
              <div><span class="risk-badge">${result.riskLevel}</span></div>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">Clinical Interpretation</div>
          <div class="interpretation">${result.interpretation}</div>
        </div>

        <div class="section">
          <div class="section-title">Management Pathway</div>
          ${Array.isArray(result.managementPathway)
            ? result.managementPathway
                .map(
                  (step: any, idx: number) => `
            <div class="management-step">
              <div class="step-number">${idx + 1}</div>
              <div>
                <strong>${step.action}</strong>
                <div style="font-size: 12px; color: #6b7280; margin-top: 4px;">${step.rationale}</div>
              </div>
            </div>
          `
                )
                .join("")
            : `<p>${result.managementPathway}</p>`
          }
        </div>

        <div class="section">
          <div class="section-title">Clinical Recommendations</div>
          ${result.recommendations
            .map(
              (rec: string) => `
            <div class="recommendation">
              <div class="recommendation-check">✓</div>
              <div>${rec}</div>
            </div>
          `
            )
            .join("")}
        </div>

        <div class="disclaimer">
          <strong>Disclaimer:</strong> This calculator is for clinical decision support only. It should not replace clinical judgment or professional medical advice. Always consult with appropriate specialists for definitive diagnosis and treatment decisions.
        </div>

        <div class="footer">
          MedResearch Academy | Clinical Decision Support Tool
        </div>
      </body>
      </html>
    `;

    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
      }, 250);
    }
  };

  const renderManagementPathway = () => {
    if (typeof result.managementPathway === "string") {
      return result.managementPathway.split("\n").map((line: string, idx: number) => (
        <div key={idx} className="flex items-start gap-3" role="listitem">
          <div
            className="w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5"
            aria-hidden="true"
          >
            {idx + 1}
          </div>
          <p className={`text-sm ${colors.text}`}>{line}</p>
        </div>
      ));
    } else if (Array.isArray(result.managementPathway)) {
      return result.managementPathway.map((step: any, idx: number) => (
        <div key={idx} className="flex items-start gap-3" role="listitem">
          <div
            className="w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5"
            aria-hidden="true"
          >
            {idx + 1}
          </div>
          <div>
            <p className={`text-sm font-semibold ${colors.text}`}>{step.action}</p>
            <p className="text-xs text-slate-600 mt-1">{step.rationale}</p>
          </div>
        </div>
      ));
    }
    return null;
  };

  return (
    <div className="space-y-6" role="region" aria-label="Calculator Results">
      {/* Main Result Card */}
      <Card
        className={`${colors.bg} border-2 ${colors.border}`}
        role="article"
        aria-labelledby="result-title"
        aria-describedby="result-interpretation"
      >
        <CardHeader>
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-4">
              <div aria-label={colors.ariaLabel} role="img">
                {getRiskIcon(result.riskLevel)}
              </div>
              <div>
                <CardTitle id="result-title" className={`text-2xl ${colors.text}`}>
                  Risk Assessment Result
                </CardTitle>
                <CardDescription className={colors.text}>{calculatorName}</CardDescription>
              </div>
            </div>
            <Badge className={colors.badge} aria-label={`Risk level: ${result.riskLevel}`}>
              <span aria-hidden="true" className="mr-1">
                {colors.pattern}
              </span>
              {result.riskLevel.toUpperCase()}
            </Badge>
          </div>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Score Display */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4" role="group" aria-label="Score summary">
            <div className="p-4 bg-white rounded-lg border border-slate-200">
              <p className="text-xs font-semibold text-slate-600 uppercase mb-2" id="score-label">
                Score
              </p>
              <p className={`text-3xl font-bold ${colors.text}`} aria-labelledby="score-label">
                {result.score}
              </p>
            </div>

            <div className="p-4 bg-white rounded-lg border border-slate-200">
              <p className="text-xs font-semibold text-slate-600 uppercase mb-2" id="risk-pct-label">
                Risk Percentage
              </p>
              <div className="flex items-center gap-2">
                <p className={`text-3xl font-bold ${colors.text}`} aria-labelledby="risk-pct-label">
                  {result.riskPercentage}%
                </p>
                <TrendingUp className={`w-6 h-6 ${colors.text}`} aria-hidden="true" />
              </div>
            </div>

            <div className="p-4 bg-white rounded-lg border border-slate-200">
              <p className="text-xs font-semibold text-slate-600 uppercase mb-2" id="risk-level-label">
                Risk Level
              </p>
              <p className={`text-xl font-bold capitalize ${colors.text}`} aria-labelledby="risk-level-label">
                <span aria-hidden="true" className="mr-2">
                  {colors.pattern}
                </span>
                {result.riskLevel}
              </p>
            </div>
          </div>

          {/* Interpretation */}
          <div className="p-4 bg-white rounded-lg border border-slate-200">
            <p className="text-xs font-semibold text-slate-600 uppercase mb-2">Clinical Interpretation</p>
            <p id="result-interpretation" className={`text-sm leading-relaxed ${colors.text}`}>
              {result.interpretation}
            </p>
          </div>

          {/* Management Pathway */}
          <div className="p-4 bg-white rounded-lg border border-slate-200">
            <p className="text-xs font-semibold text-slate-600 uppercase mb-3">Recommended Management Pathway</p>
            <div className="space-y-2" role="list" aria-label="Management steps">
              {renderManagementPathway()}
            </div>
          </div>

          {/* Recommendations */}
          <div className="space-y-3">
            <p className="text-xs font-semibold text-slate-600 uppercase">Clinical Recommendations</p>
            <div className="space-y-2" role="list" aria-label="Clinical recommendations">
              {result.recommendations.map((rec: string, idx: number) => (
                <div
                  key={idx}
                  className="p-3 bg-white rounded-lg border border-slate-200 flex items-start gap-3"
                  role="listitem"
                >
                  <div
                    className="w-5 h-5 rounded-full bg-blue-500 flex items-center justify-center text-white text-xs font-bold flex-shrink-0 mt-0.5"
                    aria-hidden="true"
                  >
                    ✓
                  </div>
                  <p className="text-sm text-slate-700">{rec}</p>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-3" role="group" aria-label="Result actions">
        <Button
          onClick={handleDownloadPDF}
          variant="default"
          className="flex-1 min-w-[140px] h-10 gap-2"
          aria-label="Download result as PDF"
        >
          <Download className="w-4 h-4" aria-hidden="true" />
          Download PDF
        </Button>
        <Button
          onClick={handlePrint}
          variant="outline"
          className="flex-1 min-w-[140px] h-10 gap-2"
          aria-label="Print or save as PDF"
        >
          <Printer className="w-4 h-4" aria-hidden="true" />
          Print
        </Button>
        <Button
          onClick={handleCopyToClipboard}
          variant="outline"
          className="flex-1 min-w-[140px] h-10 gap-2"
          aria-label={copied ? "Copied to clipboard" : "Copy result to clipboard for EMR"}
        >
          {copied ? (
            <Check className="w-4 h-4 text-green-600" aria-hidden="true" />
          ) : (
            <Copy className="w-4 h-4" aria-hidden="true" />
          )}
          {copied ? "Copied!" : "Copy for EMR"}
        </Button>
      </div>

      {/* Disclaimer */}
      <div className="p-4 bg-slate-50 rounded-lg border border-slate-200" role="note" aria-label="Important disclaimer">
        <p className="text-xs text-slate-600">
          <strong>Disclaimer:</strong> This calculator is for clinical decision support only. It should not replace
          clinical judgment or professional medical advice. Always consult with appropriate specialists for definitive
          diagnosis and treatment decisions.
        </p>
      </div>
    </div>
  );
}
